### 목표
- AND, XOR 연산을 통해 기계가 학습과 정답을 예측하는 과정을 알아보자!

### AND 연산 : 둘 다 1이면 1이 출력, 하나라도 0이면 0이 출력되는 논리 연산

In [44]:
# 기본 라이브러리 3종류 임포트
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
# sklearn : 데이터분석을 위한 머신러닝 전용 라이브러리
# sklearn 라이브러리에서 KNN 이라는 모델을 불러와보자!
from sklearn.neighbors import KNeighborsClassifier
# 학습된 모델의 신뢰성을 검증하기 위하여 평가할 수 있는 라이브러리를 가져와보자!
from sklearn import metrics

In [7]:
# 데이터를 직접 만들어보자!
df_and = pd.DataFrame([[0,0,0],
                       [0,1,0],
                       [1,0,0],
                       [1,1,1]],
                       columns= ['P', 'Q', 'P and Q']
                      )
df_and

P  Q  P and Q
0  0  0        0
1  0  1        0
2  1  0        0
3  1  1        1

In [20]:
# 인덱싱, 슬라이싱(loc,iloc)
# 문제 데이터 설정
X = df_and.iloc[ : , 0:2] # [행의 범위, 열의 범위], iloc는 끝 범위는 포함되지 않음
# 정답 데이터 설정
y = df_and.iloc[ : , 2:3] 

X= df_and.iloc[ : , 0:2]
y = df_and

In [17]:
X

P  Q
0  0  0
1  0  1
2  1  0
3  1  1

In [21]:
y

P and Q
0        0
1        0
2        0
3        1

#### KNN  분류 모델을 불러와서 변수에 담아주자!

In [22]:
# n_neighbors : 예측을 위해 판단하는 이웃 데이터의 개수
knn_model = KNeighborsClassifier(n_neighbors=1)

#### KNN 모델에 문제와 정답을 넣어서 학습시키기

In [23]:
# fit : 모델을 학습 시키는 명령, 학습을 위해 문제와 정답을 넣어주자!
knn_model.fit(X,y)

# knn_model 이라는 변수에 문제(X), 정답(y)으로 학습된 규칙이 그대로 남아있음

C:\Users\smhrd\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:179: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier(n_neighbors=1)

#### 학습된 모델을 사용하여 새로운 문제에 대해 정답을 예측하고, 답과 비교해보자!

In [27]:
# predict : 학습된 모델로 정답을 예측하는 명령
# 학습된 모델에 새로운 문제를 넣어서 예측해보자!
pre = knn_model.predict([[1,1],
                         [0,1],
                         [1,0],
                         [0,0]]
                       )
pre

array([1, 0, 0, 0], dtype=int64)

In [30]:
# 비교를 위해 실제 정답 만들기
answer = [1,0,0,1]

#### 모델 평가 진행

In [31]:
# accuracy_score : 학습된 모델의 정확도를 표현(범위 : 0~1, 1이면 100% 정확하다는 뜻)
metrics.accuracy_score(pre, answer)

0.75

#### XOR 연산 : 둘 다 같으면 0, 다르면 1이 나오는 연산

In [118]:
# 데이터를 직접 만들어보자!
df_xor = pd.DataFrame([[0,0,0],
                       [0,1,1],
                       [1,0,1],
                       [1,1,0]],
                       columns= ['P', 'Q', 'P and Q']
                      )
df_xor

P  Q  P and Q
0  0  0        0
1  0  1        1
2  1  0        1
3  1  1        0

In [119]:
X1 = df_xor.iloc[ : , 0:2]
y1 = df_xor.iloc[ : , 2:3]

In [120]:
X1

P  Q
0  0  0
1  0  1
2  1  0
3  1  1

In [121]:
y1

P and Q
0        0
1        1
2        1
3        0

In [122]:
knn_model1 = KNeighborsClassifier(n_neighbors=1)

In [123]:
knn_model1.fit(X1,y1)

C:\Users\smhrd\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:179: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier(n_neighbors=1)

In [124]:
pre1 = knn_model.predict([[1,1],
                         [0,1],
                         [1,0],
                         [0,0]]
                        )
pre1

array([0, 1, 1, 0], dtype=int64)

In [125]:
answer1 = [0,1,1,0]

In [126]:
metrics.accuracy_score(pre1, answer1)

1.0

### OR 연산

In [127]:
# 데이터를 직접 만들어보자!
df_or = pd.DataFrame([[0,0,0],
                       [0,1,1],
                       [1,0,1],
                       [1,1,0]],
                       columns= ['P', 'Q', 'P and Q']
                      )
df_or

P  Q  P and Q
0  0  0        0
1  0  1        1
2  1  0        1
3  1  1        0

In [128]:
X = df_or.iloc[ : , 0:2]
y = df_or.iloc[ : , 2:3]

In [129]:
X

P  Q
0  0  0
1  0  1
2  1  0
3  1  1

In [130]:
y

P and Q
0        0
1        1
2        1
3        0

In [131]:
knn_model2 = KNeighborsClassifier(n_neighbors=1)

In [132]:
knn_model2.fit(X,y)

C:\Users\smhrd\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:179: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier(n_neighbors=1)

In [133]:
pre = knn_model.predict([[1,1],
                         [0,1],
                         [1,0],
                         [0,0]]
                        )
pre

array([0, 1, 1, 0], dtype=int64)

In [134]:
answer = [0,1,1,0]

In [135]:
metrics.accuracy_score(pre, answer)

1.0

In [ ]:
# 데이터를 직접 만들어보자!
df_xor = pd.DataFrame([[0,0,0],
                       [0,1,1],
                       [1,0,1],
                       [1,1,0]],
                       columns= ['P', 'Q', 'P and Q']
                      )
df_xor
X1 = df_xor.iloc[ : , 0:2]
y1 = df_xor.iloc[ : , 2:3]
knn_model1 = KNeighborsClassifier(n_neighbors=1)
knn_model1.fit(X1,y1)
pre1 = knn_model.predict([[1,1],
                         [0,1],
                         [1,0],
                         [0,0]]
                        )
pre1
answer1 = [0,1,1,0]
metrics.accuracy_score(pre1, answer1)

In [ ]:
# 기본 라이브러리 3종류 임포트
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
# sklearn : 데이터분석을 위한 머신러닝 전용 라이브러리
# sklearn 라이브러리에서 KNN 이라는 모델을 불러와보자!
from sklearn.neighbors import KNeighborsClassifier
# 학습된 모델의 신뢰성을 검증하기 위하여 평가할 수 있는 라이브러리를 가져와보자!
from sklearn import metrics

df_xor = pd.DataFrame([[0,0,0],
                       [0,1,1],
                       [1,0,1],
                       [1,1,0]],
                       columns['P','Q','P and Q']
                      )
X1 = df_xor.iloc[ : , 0:2]
y1 = df_xor.iloc[ : , 2:3]
knn_model1 = KneighborsClassifier(n_neighbors=1)
knn_model1.fit(X1,y1)
## 정답 알려주기
pre1 = knn_model.predict([[1,1],
                          [0,1],
                          [1,0],
                          [0,0]]
                         )

answer1 = [0,1,1,0]
metrics.accuracy_score(pre1, answer1)

